language: go
sudo: false
go:
  - "1.11"
env:
  - GO111MODULE=on
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
