language: go
sudo: false
go:
  - "1.10"
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -v ./... --coverprofile coverage
  - $GOPATH/bin/goveralls -service=travis-ci -v -coverprofile coverage
